import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Let Me Leave</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          let me LEAVE
        </h1>

        <div className={styles.circle}>
          <div className={styles.tick}></div>
          <div className={styles.tick}></div>
          <div className={styles.tick}></div>
          <div className={styles.tick}></div>
        </div>

        <p className={styles.description} style={{display: 'flex', flexDirection: 'column'}}>
          hello, and welcome to let me leave.
          <br />
          <br />
          <button style={{display: 'block', alignSelf: 'center' }}>Sign Up</button>
          <br/>
          <button style={{ display: 'block', alignSelf: 'center' }}>Log In</button>
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          <b>Anubis</b>
        </a>
      </footer>
    </div>
  )
}
